package model;

import java.util.Objects;

public class Card {
    private final Rank rank;
    private final Suit suit;

    public Card(Rank rank, Suit suit){
        this.rank = rank;
        this.suit = suit;
    }

    public Card(Card originalCard){
        this.rank = originalCard.rank;
        this.suit = originalCard.suit;
    }

    public String getString(){
        return rank.name() + " of " + suit.name();
    }

    @Override
    public boolean equals(Object o) {
        // generated by intellij
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Card card = (Card) o;
        return rank == card.rank && suit == card.suit;
    }
}
